# Site settings
title: OpenElectoralCommission
email: OpenElectoralCommission@democracyclub.org.uk
description: Easily reusable details of political parties, lovingly rescued from the impenetrable Electoral Commission
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openelectoralcommission.org.uk" # the base hostname & protocol for your site
twitter_username: democlub
github_username:  democracyclub

# Build settings
markdown: kramdown
